Which of the following filters are seperable?

In [1]:
A = [[3, 2, 4], 
     [2, 1, 3], 
     [6, 4, 8]]
B = [[4, 2, 8], 
     [2, 1, 4], 
     [6, 3, 12]]
C = [[4, 2, 8],
     [-2, -1, -4], 
     [6, 3, 12]]

Seperability of a $nxn$ filter means, that it can be separated into two partial filters.

Of the matrices, A cannot be separated. B and C can be separated.

In [19]:
import numpy as np

B1 = np.array([[2],
               [1],
               [3]])
B2 = np.array([2, 1, 4])
print(B1 * B2)

[[ 4  2  8]
 [ 2  1  4]
 [ 6  3 12]]


In [20]:
C1 = np.array([[2],
               [-1],
               [3]])
C2 = np.array([2, 1, 4])
print(C1 * C2)

[[ 4  2  8]
 [-2 -1 -4]
 [ 6  3 12]]


3 Sampling

If we take a photo or artificially produce an image the continuous
distribution of light is sampled by the image grid.
What does the sampling theorem (Chapter 2, p. 15) tell us?
We can consider the signal to be composed of sine waves.
In case of images it means that every image can be represented as a
weighted sum of images like this:
(Image of diagonally aligned sine waves)
and that we have to place at least two sampling points per period
(Chapter 2, p. 14).
Therefore the higher frequencies our image contains the denser the image
grid has to be.
In any given grid the wavelength of the representable wave with maximum
frequency is 2 grid spacings B: f=1/2B.
Assume you image a point. After removing all frequencies higher than 1/2
this point is represented by the function
(Function)